services:
  sophia-medication-service:
    build: .
    container_name: sophia-medication-service
    ports:
      - '3003:3000'
    depends_on:
      - medication-postgres
    restart: always

  medication-postgres:
    image: postgres:15
    container_name: medication-postgres
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - medication_postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  medication_postgres_data:
